package ctrmap.formats.h3d;

public class BCHContentHeader {

	public int modelsPointerTableOffset;
	public int modelsPointerTableEntries;
	public int modelsNameOffset;
	public int materialsPointerTableOffset;
	public int materialsPointerTableEntries;
	public int materialsNameOffset;
	public int shadersPointerTableOffset;
	public int shadersPointerTableEntries;
	public int shadersNameOffset;
	public int texturesPointerTableOffset;
	public int texturesPointerTableEntries;
	public int texturesNameOffset;
	public int materialsLUTPointerTableOffset;
	public int materialsLUTPointerTableEntries;
	public int materialsLUTNameOffset;
	public int lightsPointerTableOffset;
	public int lightsPointerTableEntries;
	public int lightsNameOffset;
	public int camerasPointerTableOffset;
	public int camerasPointerTableEntries;
	public int camerasNameOffset;
	public int fogsPointerTableOffset;
	public int fogsPointerTableEntries;
	public int fogsNameOffset;
	public int skeletalAnimationsPointerTableOffset;
	public int skeletalAnimationsPointerTableEntries;
	public int skeletalAnimationsNameOffset;
	public int materialAnimationsPointerTableOffset;
	public int materialAnimationsPointerTableEntries;
	public int materialAnimationsNameOffset;
	public int visibilityAnimationsPointerTableOffset;
	public int visibilityAnimationsPointerTableEntries;
	public int visibilityAnimationsNameOffset;
	public int lightAnimationsPointerTableOffset;
	public int lightAnimationsPointerTableEntries;
	public int lightAnimationsNameOffset;
	public int cameraAnimationsPointerTableOffset;
	public int cameraAnimationsPointerTableEntries;
	public int cameraAnimationsNameOffset;
	public int fogAnimationsPointerTableOffset;
	public int fogAnimationsPointerTableEntries;
	public int fogAnimationsNameOffset;
	public int scenePointerTableOffset;
	public int scenePointerTableEntries;
	public int sceneNameOffset;
}
